sudo: false
language: ruby
rvm:
  - rbx-2
  #- 1.9.3
  #- 2.0.0
  #- 2.1.0
  ## JRuby is not compatible, see Gemfile for details.
  # - jruby-19mode
  # - jruby-head
env:
  global:
    - DB=postgresql
    - BUNDLE_JOBS=4
matrix:
  allow_failures:
    - rvm: rbx-2

before_install:
  - gem install bundler -v '>= 1.7.7'
  - bundler --version
  - ruby ci/copy_database_config.rb
install: bundle install --retry=3 --jobs=4

before_script:
  - psql -c 'create database calagator_test;' -U postgres
  - bundle exec rake db:migrate
  - cp "config/secrets.yml.sample" "config/secrets.yml"
  - bundle exec rake sunspot:solr:start
script:
  - bundle exec rake spec --trace
#cache: bundler

